version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-api
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      DB_STRING_CONNECTION: "mongodb://root:toor@mongo:27017/whatsapp?authSource=admin"
      DB_LOG: "false"
      DB_DATABASE: "wpp"
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  mongo_data:
